eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
spring:
  application:
    name: openfeign-consumer
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
      retry:
        enabled: true