eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: openfeign-consumer-route
          uri: lb://openfeign-consumer
          predicates:
            - Path=/index
          filters:
            - name: Post
server:
  port: 80
