spring:
  application:
    name: demo-springboot-dubbo-provider

dubbo:
  application:
    name: demo-springboot-dubbo-provider
  scan:
    base-packages: com.accelerator.demo.springboot.dubbo.provider.impl
  registry:
    address: zookeeper://localhost:2181
    simplified: true
  protocol:
    name: dubbo
  config:
    multiple: false





