spring:
  application:
    name: demo-springboot-dubbo-consumer

dubbo:
  application:
    name: demo-springboot-dubbo-consumer
  scan:
    base-packages: com.accelerator.demo.springboot.dubbo.consumer.client
  registry:
    address: zookeeper://localhost:2181
    simplified: true
  protocol:
    name: dubbo
  config:
    multiple: false